export interface WorkspaceTemplate {
  id: string;
  title: string;
  description: string;
  language: string;
  packages: string[];
  code: string;
}

export const TEMPLATES: WorkspaceTemplate[] = [
  {
    id: 'blank',
    title: 'Blank Python',
    description: 'Start from scratch',
    language: 'python',
    packages: [],
    code: '# Write your Python code here\nprint("Hello from BioDockify Workspace!")\n',
  },
  {
    id: 'rdkit-basic',
    title: 'Your First Molecule (RDKit)',
    description: 'Create and analyze a caffeine molecule',
    language: 'python',
    packages: ['rdkit'],
    code: [
      'from rdkit import Chem',
      'from rdkit.Chem import Descriptors, rdMolDescriptors',
      '',
      '# Create caffeine molecule from SMILES',
      'caffeine = Chem.MolFromSmiles("CN1C=NC2=C1C(=O)N(C(=O)N2C)C")',
      '',
      '# Calculate molecular properties',
      'print(f"Name: Caffeine")',
      'print(f"SMILES: {Chem.MolToSmiles(caffeine)}")',
      'print(f"Formula: {rdMolDescriptors.CalcMolFormula(caffeine)}")',
      'print(f"Molecular Weight: {Descriptors.MolWt(caffeine):.2f}")',
      'print(f"logP: {Descriptors.MolLogP(caffeine):.2f}")',
      'print(f"H-Bond Donors: {Descriptors.NumHDonors(caffeine)}")',
      'print(f"H-Bond Acceptors: {Descriptors.NumHAcceptors(caffeine)}")',
    ].join('\n'),
  },
  {
    id: 'lipinski',
    title: "Lipinski's Rule of Five Checker",
    description: 'Check drug-likeness of molecules',
    language: 'python',
    packages: ['rdkit'],
    code: [
      'from rdkit import Chem',
      'from rdkit.Chem import Descriptors, Lipinski',
      '',
      'def check_lipinski(smiles, name=""):',
      '    mol = Chem.MolFromSmiles(smiles)',
      '    if not mol:',
      '        return f"{name}: Invalid SMILES"',
      '    mw = Descriptors.MolWt(mol)',
      '    logp = Descriptors.MolLogP(mol)',
      '    hbd = Lipinski.NumHDonors(mol)',
      '    hba = Lipinski.NumHAcceptors(mol)',
      '    passes = mw <= 500 and logp <= 5 and hbd <= 5 and hba <= 10',
      '    status = "PASS" if passes else "FAIL"',
      '    return f"{name}: MW={mw:.1f} logP={logp:.1f} HBD={hbd} HBA={hba} -> {status}"',
      '',
      '# Check common drugs',
      'drugs = [',
      '    ("Aspirin", "CC(=O)OC1=CC=CC=C1C(=O)O"),',
      '    ("Ibuprofen", "CC(C)CC1=CC=C(C=C1)CC(C)C(=O)O"),',
      '    ("Caffeine", "CN1C=NC2=C1C(=O)N(C(=O)N2C)C"),',
      ']',
      '',
      'for name, smi in drugs:',
      '    print(check_lipinski(smi, name))',
    ].join('\n'),
  },
  {
    id: 'pandas-pharma',
    title: 'Drug Data Analysis (Pandas)',
    description: 'Analyze a dataset of drug properties',
    language: 'python',
    packages: ['pandas', 'matplotlib'],
    code: [
      'import pandas as pd',
      'import matplotlib.pyplot as plt',
      '',
      '# Sample drug data',
      'data = {',
      "    'drug': ['Aspirin', 'Ibuprofen', 'Paracetamol', 'Naproxen', 'Diclofenac'],",
      "    'mw': [180.16, 206.28, 151.16, 230.26, 296.15],",
      "    'logp': [1.19, 3.97, 0.46, 3.18, 4.51],",
      "    'solubility': [4.6, 0.08, 14.0, 0.02, 0.003],",
      '}',
      '',
      'df = pd.DataFrame(data)',
      '',
      'print("Dataset:")',
      'print(df)',
      'print()',
      'print("Statistics:")',
      'print(df.describe())',
      'print()',
      'print(f"Highest logP: {df.loc[df[' + "'logp'" + '].idxmax(), ' + "'drug'" + ']}")',
      'print(f"Most soluble: {df.loc[df[' + "'solubility'" + '].idxmax(), ' + "'drug'" + ']}")',
      '',
      '# Plot molecular weight vs logP',
      'plt.figure(figsize=(8, 5))',
      'plt.scatter(df["mw"], df["logp"], s=100, c="emerald")',
      'for i, row in df.iterrows():',
      '    plt.annotate(row["drug"], (row["mw"], row["logp"]), ',
      '                xytext=(5, 5), textcoords="offset points")',
      'plt.xlabel("Molecular Weight")',
      'plt.ylabel("logP")',
      'plt.title("Drug Properties: MW vs logP")',
      'plt.grid(True, alpha=0.3)',
      'plt.show()',
    ].join('\n'),
  },
  {
    id: 'numpy-qsar',
    title: 'Simple QSAR Model (NumPy)',
    description: 'Build a linear regression for drug activity',
    language: 'python',
    packages: ['numpy', 'matplotlib'],
    code: [
      'import numpy as np',
      'import matplotlib.pyplot as plt',
      '',
      '# Simulated QSAR data: logP vs biological activity (pIC50)',
      'logP = np.array([1.0, 2.5, 3.0, 0.5, 4.0, 2.0, 3.5, 1.5, 2.8, 3.2])',
      'activity = np.array([5.2, 7.8, 8.1, 3.9, 8.5, 6.5, 7.9, 4.8, 7.2, 7.6])',
      '',
      '# Linear regression: y = mx + b',
      'coeffs = np.polyfit(logP, activity, 1)',
      'm, b = coeffs',
      '',
      'print(f"QSAR Model: Activity = {m:.3f} * logP + {b:.3f}")',
      'print(f"Correlation (r): {np.corrcoef(logP, activity)[0,1]:.4f}")',
      '',
      '# Predict activity for a new compound',
      'new_logp = 3.7',
      'predicted = m * new_logp + b',
      'print(f"Predicted activity for logP={new_logp}: {predicted:.2f}")',
      '',
      '# Plot',
      'plt.figure(figsize=(8, 5))',
      'plt.scatter(logP, activity, s=80, c="blue", label="Observed")',
      'x_line = np.linspace(0, 5, 100)',
      'plt.plot(x_line, m * x_line + b, "r--", label=f"y = {m:.2f}x + {b:.2f}")',
      'plt.xlabel("logP")',
      'plt.ylabel("Biological Activity (pIC50)")',
      'plt.title("QSAR: Linear Regression Model")',
      'plt.legend()',
      'plt.grid(True, alpha=0.3)',
      'plt.show()',
    ].join('\n'),
  },
  {
    id: 'smiles-parse',
    title: 'SMILES Parser & Substructure Search',
    description: 'Parse molecules and search for patterns',
    language: 'python',
    packages: ['rdkit'],
    code: [
      'from rdkit import Chem',
      '',
      '# A library of common drug SMILES',
      'drugs = {',
      '    "Aspirin": "CC(=O)OC1=CC=CC=C1C(=O)O",',
      '    "Ibuprofen": "CC(C)CC1=CC=C(C=C1)CC(C)C(=O)O",',
      '    "Paracetamol": "CC(=O)NC1=CC=C(C=C1)O",',
      '    "Caffeine": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",',
      '    "Penicillin": "CC1(C)SC2C(NC(=O)Cc3ccccc3)C(=O)N2C1C(=O)O",',
      '}',
      '',
      '# Parse all molecules',
      'mols = {name: Chem.MolFromSmiles(smi) for name, smi in drugs.items()}',
      'print("Parsed molecules:")',
      'for name, mol in mols.items():',
      '    if mol:',
      '        print(f"  {name}: {mol.GetNumAtoms()} atoms, {mol.GetNumBonds()} bonds")',
      '    else:',
      '        print(f"  {name}: PARSE ERROR")',
      '',
      '# Substructure search: find all molecules with a carboxylic acid',
      'cooh = Chem.MolFromSmarts("C(=O)O")',
      'print("\\nMolecules with carboxylic acid (-COOH):")',
      'for name, mol in mols.items():',
      '    if mol and mol.HasSubstructMatch(cooh):',
      '        print(f"  {name}: MATCH")',
    ].join('\n'),
  },
];
