export interface WorkspaceTemplate {
  id: string;
  title: string;
  description: string;
  language: string;
  packages: string[];
  code: string;
}

export const TEMPLATES: WorkspaceTemplate[] = [
  {
    id: 'blank',
    title: 'Blank Python',
    description: 'Start from scratch',
    language: 'python',
    packages: [],
    code: '# Write your Python code here\nprint("Hello from BioDockify Workspace!")\n',
  },
  {
    id: 'biopython-dna',
    title: 'DNA & Peptide Analysis (BioPython)',
    description: 'Transcription, translation & peptide properties',
    language: 'python',
    packages: ['biopython'],
    code: [
      'from Bio.Seq import Seq',
      'from Bio.SeqUtils.ProtParam import ProteinAnalysis',
      '',
      '# Target drug gene coding sequence (e.g. insulin snippet)',
      'coding_dna = Seq("ATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGAACCAACAC")',
      '',
      'print("=== DNA SEQUENCE ANALYSIS ===")',
      'print(f"DNA Sequence Length: {len(coding_dna)} bp")',
      'print(f"GC Content: {(coding_dna.count(\x27G\x27) + coding_dna.count(\x27C\x27)) / len(coding_dna) * 100:.1f}%")',
      '',
      '# Transcribe & Translate',
      'mrna = coding_dna.transcribe()',
      'protein = coding_dna.translate()',
      'print(f"mRNA: {mrna}")',
      'print(f"Peptide Sequence: {protein}")',
      '',
      '# Protein Biophysical Properties',
      'analyzed_seq = ProteinAnalysis(str(protein))',
      'print("\\n=== PEPTIDE PROPERTIES ===")',
      'print(f"Molecular Weight: {analyzed_seq.molecular_weight():.2f} Da")',
      'print(f"Isoelectric Point (pI): {analyzed_seq.isoelectric_point():.2f}")',
      'print(f"Aromaticity: {analyzed_seq.aromaticity() * 100:.1f}%")',
      'print(f"Instability Index: {analyzed_seq.instability_index():.2f}")',
    ].join('\n'),
  },
  {
    id: 'lipinski',
    title: "Lipinski's Rule of 5 Checker",
    description: 'Assess drug-likeness & oral bioavailability parameters',
    language: 'python',
    packages: ['pandas'],
    code: [
      'import pandas as pd',
      '',
      '# Lipinski Rule of 5 parameters for common therapeutic agents',
      'drugs_data = [',
      '    {"Drug": "Aspirin", "MW": 180.16, "LogP": 1.19, "HBD": 1, "HBA": 3, "RotBonds": 3},',
      '    {"Drug": "Ibuprofen", "MW": 206.28, "LogP": 3.97, "HBD": 1, "HBA": 2, "RotBonds": 4},',
      '    {"Drug": "Paracetamol", "MW": 151.16, "LogP": 0.46, "HBD": 2, "HBA": 2, "RotBonds": 1},',
      '    {"Drug": "Atorvastatin", "MW": 558.64, "LogP": 5.70, "HBD": 4, "HBA": 6, "RotBonds": 12},',
      '    {"Drug": "Caffeine", "MW": 194.19, "LogP": -0.07, "HBD": 0, "HBA": 6, "RotBonds": 0},',
      '    {"Drug": "Remdesivir", "MW": 602.58, "LogP": 1.90, "HBD": 4, "HBA": 12, "RotBonds": 13},',
      ']',
      '',
      'df = pd.DataFrame(drugs_data)',
      '',
      'def evaluate_ro5(row):',
      '    violations = 0',
      '    if row["MW"] > 500: violations += 1',
      '    if row["LogP"] > 5: violations += 1',
      '    if row["HBD"] > 5: violations += 1',
      '    if row["HBA"] > 10: violations += 1',
      '    return "PASS" if violations <= 1 else f"FAIL ({violations} violations)"',
      '',
      'df["Lipinski_Ro5"] = df.apply(evaluate_ro5, axis=1)',
      '',
      'print("=== LIPINSKI RULE OF FIVE (Ro5) DRUG-LIKENESS EVALUATION ===")',
      'print(df.to_string(index=False))',
    ].join('\n'),
  },
  {
    id: 'pandas-pharma',
    title: 'Drug Data Analysis (Pandas & Matplotlib)',
    description: 'Analyze drug dataset and plot MW vs LogP',
    language: 'python',
    packages: ['pandas', 'matplotlib'],
    code: [
      'import pandas as pd',
      'import matplotlib.pyplot as plt',
      '',
      '# Sample pharmaceutical dataset',
      'data = {',
      "    'drug': ['Aspirin', 'Ibuprofen', 'Paracetamol', 'Naproxen', 'Diclofenac', 'Omeprazole'],",
      "    'mw': [180.16, 206.28, 151.16, 230.26, 296.15, 345.42],",
      "    'logp': [1.19, 3.97, 0.46, 3.18, 4.51, 2.23],",
      "    'solubility_mg_ml': [4.6, 0.08, 14.0, 0.02, 0.003, 0.18],",
      '}',
      '',
      'df = pd.DataFrame(data)',
      'print("=== PHARMACEUTICAL DATASET ===")',
      'print(df)',
      'print("\\n=== SUMMARY STATISTICS ===")',
      'print(df.describe())',
      '',
      '# Plot Molecular Weight vs logP',
      'plt.figure(figsize=(7, 4.5))',
      'plt.scatter(df["mw"], df["logp"], s=120, c="#10b981", edgecolors="#047857", linewidth=1.5)',
      'for _, row in df.iterrows():',
      '    plt.annotate(row["drug"], (row["mw"], row["logp"]), textcoords="offset points", xytext=(6, 4), fontsize=9)',
      'plt.axhline(5.0, color="red", linestyle="--", alpha=0.6, label="Ro5 Max LogP (5.0)")',
      'plt.axvline(500.0, color="orange", linestyle="--", alpha=0.6, label="Ro5 Max MW (500 Da)")',
      'plt.xlabel("Molecular Weight (Da)")',
      'plt.ylabel("LogP (Lipophilicity)")',
      'plt.title("Drug Candidates: MW vs LogP Distribution")',
      'plt.legend(loc="upper left", fontsize=8)',
      'plt.grid(True, alpha=0.25)',
      'plt.tight_layout()',
      'plt.show()',
    ].join('\n'),
  },
  {
    id: 'numpy-qsar',
    title: 'QSAR Regression (NumPy, Scikit-Learn, Matplotlib)',
    description: 'Train a regression model predicting pIC50 drug activity',
    language: 'python',
    packages: ['numpy', 'scikit-learn', 'matplotlib'],
    code: [
      'import numpy as np',
      'import matplotlib.pyplot as plt',
      'from sklearn.linear_model import LinearRegression',
      'from sklearn.metrics import r2_score, mean_squared_error',
      '',
      '# Molecular descriptors (LogP) vs experimental biological activity (pIC50)',
      'np.random.seed(42)',
      'logP = np.array([1.1, 1.8, 2.2, 2.7, 3.1, 3.5, 3.9, 4.2, 4.7, 5.0, 5.4, 5.8]).reshape(-1, 1)',
      'pIC50 = 2.4 * logP.squeeze() + 1.8 + np.random.normal(0, 0.45, size=len(logP))',
      '',
      '# Fit QSAR model',
      'model = LinearRegression()',
      'model.fit(logP, pIC50)',
      'pIC50_pred = model.predict(logP)',
      '',
      'r2 = r2_score(pIC50, pIC50_pred)',
      'rmse = np.sqrt(mean_squared_error(pIC50, pIC50_pred))',
      '',
      'print("=== QSAR LINEAR MODEL ===")',
      'print(f"Formula: pIC50 = {model.coef_[0]:.3f} * LogP + {model.intercept_:.3f}")',
      'print(f"R-squared (R2): {r2:.4f}")',
      'print(f"RMSE: {rmse:.4f}")',
      '',
      '# Predict for a candidate molecule',
      'candidate_logp = np.array([[3.8]])',
      'candidate_pIC50 = model.predict(candidate_logp)[0]',
      'print(f"Predicted pIC50 for LogP=3.8: {candidate_pIC50:.2f} (IC50 = {10**(-candidate_pIC50) * 1e9:.1f} nM)")',
      '',
      '# Plot QSAR fit',
      'plt.figure(figsize=(7, 4.5))',
      'plt.scatter(logP, pIC50, color="#3b82f6", s=80, label="Observed Compounds")',
      'plt.plot(logP, pIC50_pred, color="#ef4444", linewidth=2, label=f"Fit (R² = {r2:.2f})")',
      'plt.xlabel("LogP (Calculated)")',
      'plt.ylabel("Biological Activity (pIC50)")',
      'plt.title("QSAR Model: Activity Prediction")',
      'plt.legend()',
      'plt.grid(True, alpha=0.25)',
      'plt.tight_layout()',
      'plt.show()',
    ].join('\n'),
  },
  {
    id: 'enzyme-kinetics',
    title: 'Enzyme Kinetics (SciPy & Matplotlib)',
    description: 'Fit Michaelis-Menten kinetics to calculate Vmax and Km',
    language: 'python',
    packages: ['scipy', 'numpy', 'matplotlib'],
    code: [
      'import numpy as np',
      'import matplotlib.pyplot as plt',
      'from scipy.optimize import curve_fit',
      '',
      '# Michaelis-Menten equation: v = (Vmax * [S]) / (Km + [S])',
      'def michaelis_menten(s, vmax, km):',
      '    return (vmax * s) / (km + s)',
      '',
      '# Experimental substrate concentrations (uM) and reaction rates (umol/min)',
      'substrate = np.array([2.5, 5.0, 10.0, 20.0, 40.0, 80.0, 120.0, 200.0])',
      'rate_observed = np.array([12.1, 21.4, 34.2, 49.5, 63.8, 74.1, 79.8, 83.2])',
      '',
      '# Fit non-linear curve',
      'params, covariance = curve_fit(michaelis_menten, substrate, rate_observed, p0=[100, 20])',
      'vmax_fit, km_fit = params',
      '',
      'print("=== ENZYME KINETICS PARAMETERS ===")',
      'print(f"Estimated Vmax: {vmax_fit:.2f} umol/min")',
      'print(f"Estimated Km:   {km_fit:.2f} uM")',
      '',
      '# Plot curve fit',
      's_fine = np.linspace(0, 220, 200)',
      'rate_fit = michaelis_menten(s_fine, vmax_fit, km_fit)',
      '',
      'plt.figure(figsize=(7, 4.5))',
      'plt.scatter(substrate, rate_observed, color="#8b5cf6", s=80, label="Assay Data Points")',
      'plt.plot(s_fine, rate_fit, color="#10b981", linewidth=2, label=f"M-M Fit (Vmax={vmax_fit:.1f}, Km={km_fit:.1f})")',
      'plt.axhline(vmax_fit, color="gray", linestyle=":", alpha=0.7, label=f"Vmax ({vmax_fit:.1f})")',
      'plt.axvline(km_fit, color="orange", linestyle=":", alpha=0.7, label=f"Km ({km_fit:.1f} uM)")',
      'plt.xlabel("Substrate Concentration [S] (µM)")',
      'plt.ylabel("Initial Velocity v (µmol/min)")',
      'plt.title("Enzyme Kinetics: Michaelis-Menten Fitting")',
      'plt.legend(loc="lower right", fontsize=8)',
      'plt.grid(True, alpha=0.25)',
      'plt.tight_layout()',
      'plt.show()',
    ].join('\n'),
  },
];
